services:
  backend:
    build:
      context: ./backend
      args:
        - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    restart: unless-stopped
    environment:
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
    networks:
      - whisper-net
    volumes:
      - ./backend/:/app
      - shared-uploads:/uploads
    command: python3 app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 10
  frontend:
    build: ./frontend # Path to your Next.js frontend
    ports:
      - "3000:3000"
    networks:
      - whisper-net
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - shared-uploads:/app/uploads
    command: npm run start

networks:
  whisper-net: # Custom network
    driver: bridge

volumes:
  shared-uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend/speech2text/uploads
