#FROM ghcr.io/opennmt/ctranslate2:4.4.0-ubuntu22.04-cuda12.2
FROM ghcr.io/opennmt/ctranslate2:4.6.2-ubuntu22.04-cuda12.2

# Set working directory
WORKDIR /app

RUN apt-get update && \
    apt-get install -y software-properties-common

RUN add-apt-repository ppa:ubuntuhandbook1/ffmpeg6 &&  \ 
    apt-get update && \
    apt-get install -y ffmpeg libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev


RUN apt-get update && \
    apt-get install -y \
    python3-dev \
    python3-venv \
    build-essential \
    curl \
    patch \
    pkg-config

# Create the virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV

# "Activate" the venv by prioritizing its binaries in the system PATH
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

#RUN ffmpeg -version && ffprobe -version

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip setuptools wheel Cython

RUN pip install \
    --no-cache-dir \
    --no-build-isolation \
    -r requirements.txt

RUN pip install --no-cache-dir \
    -U transformers

COPY models.py .

# Pass Hugging Face token as build arg and set as env
ARG HUGGING_FACE_TOKEN
ARG MODELS_DOWNLOAD_PATH

ENV HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
ENV MODELS_DOWNLOAD_PATH=${MODELS_DOWNLOAD_PATH}
ENV TORCH_HOME="${MODELS_DOWNLOAD_PATH}/torch"
ENV XDG_CACHE_HOME="${MODELS_DOWNLOAD_PATH}/xdg"
ENV PYANNOTE_CACHE="${MODELS_DOWNLOAD_PATH}/pyannote"

# Download model at build time
RUN python3 models.py

ENTRYPOINT []