FROM ghcr.io/opennmt/ctranslate2:4.4.0-ubuntu20.04-cuda12.2

# Set working directory
WORKDIR /app

# Install system dependencies in one layer and clean up
RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    rm -rf /var/lib/apt/lists/*

COPY . .
# Upgrade pip before installing
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Pass Hugging Face token as build arg and set as env
ARG HUGGING_FACE_TOKEN
ENV HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}

# Set CTranslate2 model cache directory
ENV CTRANSLATE2_CACHE_DIR=/app/models

# Download model at build time
RUN python3 models.py

ENTRYPOINT []