FROM ghcr.io/opennmt/ctranslate2:4.4.0-ubuntu20.04-cuda12.2

# Set working directory
WORKDIR /app

# Install system dependencies in one layer and clean up
RUN apt-get update && \
    apt-get install -y ffmpeg curl patch && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
# Upgrade pip before installing
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt &&\
    pip install --no-cache-dir transformers -U

COPY models.py .

# Pass Hugging Face token as build arg and set as env
ARG HUGGING_FACE_TOKEN
ARG MODELS_DOWNLOAD_PATH

ENV HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
ENV MODELS_DOWNLOAD_PATH=${MODELS_DOWNLOAD_PATH}
ENV TORCH_HOME="${MODELS_DOWNLOAD_PATH}/torch"
ENV XDG_CACHE_HOME="${MODELS_DOWNLOAD_PATH}/xdg"
ENV PYANNOTE_CACHE="${MODELS_DOWNLOAD_PATH}/pyannote"

# Download model at build time
RUN python3 models.py

ENTRYPOINT []